
import type { Asset } from '../types/video';
import { saveAsset } from '../utils/db';
import { extractPeaks } from '../utils/audio';

export async function generateTTS(text: string, voiceId?: string, voiceName?: string): Promise<Asset | null> {
  try {
    const response = await fetch('/api/tts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ text, voiceId, voiceName }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to generate TTS');
    }

    const audioBlob = await response.blob();
    
    const asset: Asset = {
      id: `tts_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
      name: `Voiceover: ${text.slice(0, 20)}...`,
      type: 'audio',
      url: '', // Will be generated by URL.createObjectURL in the UI or db util
      createdAt: Date.now(),
      peaks: await extractPeaks(audioBlob, 40)
    };

    await saveAsset(asset, audioBlob);
    return asset;
  } catch (error) {
    console.error('TTS Generation Error:', error);
    throw error;
  }
}
